[package]
name = "fmbb"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
config = "0.13.3"
paho-mqtt = "0.12.1"
serde = { version = "1.0.158", features = ["derive"] }
tokio = { version = "1.27.0", features = ["full"] }
toml = "0.7.3"
