# seconds to wait for inflight publications to be delivered/acknoledged after
# all publications was sent
wait = 10

[[publishers]] 
broker = "localhost:1883"
clients = 1 
rate = 50 
count = 1000

[[subscribers]]
broker = "localhost:1883"
clients = 500
